# Generated by Django 3.1.3 on 2021-03-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
