langage: python
python:
        - "3.7.4"

branches:
    only:
        - stage

install:
        - pip install -r requirements.txt

services:
        - postgresql

env: DJANGO_SETTINGS_MODULE="startup_pur_beurre.settings.travis"

script:
        - pytest
