langage: python
python:
        - "3.7.4"

branches:
    only:
        - stage

before_script:
        - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip88.0.4324.96
        - unzip chromedriver_linux64.zip -d /home/thomas/pur-beurre
        - export CHROME_BIN=chromium-browser


install:
        - pip install -r requirements.txt

services:
        - postgresql

env: DJANGO_SETTINGS_MODULE="startup_pur_beurre.settings.travis"

script:
        - pytest
