langage: python

python:
        - '3.7.4'

before_script:
        - pip install -r requirements.txt

branches:
    only:
        - stage

env: DJANGO_SETTINGS_MODULE="pur-beurre.settings.travis"

services:
        - postgresql

script:
        - pytest
