langage: python
python:
        - "3.7.4"

branches:
    only:
        - stage

install:
        - psql -c 'create user thoms;'
        - psql -c 'ALTER USER thoms SUPERUSER;'
        - psql -c 'create database pur_beurre_db;'
        - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -P ~/
        - unzip chromedriver_linux64.zip -d ~/
        - export CHROME_BIN=chromium-browser
        - pip install -r requirements.txt

services:
        - postgresql

env: DJANGO_SETTINGS_MODULE="startup_pur_beurre.settings.travis"

script:
        - pytest
