langage: python
python:
        - "3.7.4"

branches:
    only:
        - stage

install:
        - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - PATH=$PATH:~/
        - pip install -r requirements.txt

services:
        - postgresql

before_script:
        - psql -c 'create user thoms;'
        - psql -c 'ALTER USER thoms SUPERUSER;'
        - psql -c 'create database pur_beurre_db;'
        - psql -c '\q;'
        - python manage.py migrate
        - psql -c 'pur_beurre_db;'
        - psql -c "INSERT INTO Products VALUES ('selenium', 'frosties', 'frosties de kelloggs', 'carrouf', 'a', '0.1','0.1', '0.1', '0.1', 'https://static.openfoodfacts.org/images/products/505/382/710/4081/front_fr.89.full.jpg', 'https://fr.openfoodfacts.org/produit/5053827104081/frosties-kellogg-s');"

env: DJANGO_SETTINGS_MODULE="startup_pur_beurre.settings.travis"

script:
        - pytest
