# Generated by Django 3.1.3 on 2020-12-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=20)),
                ('name', models.TextField(null=True)),
                ('brand', models.TextField()),
                ('store', models.TextField(null=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat_lipids_100g', models.CharField(max_length=10)),
                ('saturated_fatty_acids_100g', models.CharField(max_length=10)),
                ('sugar_100g', models.CharField(max_length=10)),
                ('salt_100g', models.CharField(max_length=10)),
                ('photo', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.products')),
            ],
        ),
    ]
