# Generated by Django 3.1.3 on 2020-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('store', models.TextField()),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat_lipids_100g', models.CharField(max_length=10)),
                ('saturated_fatty_acids_100g', models.CharField(max_length=10)),
                ('sugar_100g', models.CharField(max_length=10)),
                ('salt_100g', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('e_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='database.Products', verbose_name='Product ID')),
                ('user', models.ManyToManyField(to='database.Users', verbose_name='User ID')),
            ],
        ),
    ]
