# Generated by Django 3.1.3 on 2020-11-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201124_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='savedproducts',
            name='user',
        ),
        migrations.AddField(
            model_name='savedproducts',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.products'),
        ),
        migrations.AddField(
            model_name='savedproducts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.users'),
        ),
    ]
