# Generated by Django 3.1.3 on 2020-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201126_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.TextField(null=True),
        ),
    ]
