# Generated by Django 3.1.3 on 2020-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201202_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.URLField(max_length=250),
        ),
    ]
